idf_component_register(
    SRCS
        "main.c"
        "backlight/backlight.c"
        "display/display.c"
        "expander/expander.c"
        "wifi/wifiscan.c"
        "wifi/wifistation.c"
        "gui/gui.c"
        "gui/screens/screen_settings.c"
        "gui/screens/screen_environment.c"
        "gui/screens/screen_wifi.c"
        "gui/screens/screen_1.c"
        "gui/screens/screen_2.c"
        "i2c/i2c.c"
        "rgblcd43b/rgblcd43b"
    INCLUDE_DIRS 
        "."
        "backlight"
        "display"
        "expander"
        "wifi"
        "gui"
        "gui/screens"
        "i2c"
        "rgblcd43b"
    REQUIRES
        esp_lcd
        lvgl
        esp_lcd_touch
        esp_lcd_touch_gt911
        esp_driver_i2c
        esp_common
        esp_wifi
        nvs_flash
    )
